### ISSUE TITLE
Black screen on Buzz Lightyear of Star Command

### ISSUE THREAD

**Issue by GoogleCodeExporter** [piorrro33/psxjin#52]
```
What steps will reproduce the problem?
1. Load the game Buzz Lightyear of Star Command
2. After some credits text appears, the screen will be black
3.

What is the expected output? What do you see instead?
The expected output is the FMVs and the game menu, instead I get a black screen.

What version of the product are you using? On what operating system?
PSXjin v.2.0.2 svn0. Windows 7 Starter 32-bit

Please provide any additional information below.


```

Original issue reported on code.google.com by `unit.27...@gmail.com` on 24 Jan 2015 at 5:52

**Comment by vgturtle127** [comment]
This could be a problem with Windows 7 Starter. Earlier builds had trouble with DirectX, and even later builds had problems with DirectDraw. More research required.

**Comment by piorrro33** [comment]
I'll build a VM with Win7 starter and see if it's fixed.

**Comment by vgturtle127** [comment]
Alright. I would, but I have 64MB left on my hard drive. :laughing:

**Comment by piorrro33** [comment]
Ok, I finally have my VM set up working. I will finally be able to test this out! *yay*

**Comment by piorrro33** [comment]
First of all, finding this game is really hard, plus we don't know which ROM he got, PAL/NTSC-U/J etc.
So I found an NTSC version of the game, that I will test ASAP (when the download will be done...)

**Comment by vgturtle127** [comment]
Good work!
