### ISSUE TITLE
Move to another site like GitHub or SourceForge?

### ISSUE THREAD

**Issue by GoogleCodeExporter** [piorrro33/psxjin#53]
```
I just realized that soon Google Code is being shut down. I didn't see anything 
about it anywhere on this Google Code page, so I thought I would mention it 
just in case. I really like this, and would like to contribute and stuff, but 
we should migrate to something else soon.

March 12, 2015 - New project creation disabled

August 24, 2015 - The site goes read-only, can still checkout/view project 
source, issues, and wikis.

January 25, 2016 - The project hosting service is closed. You will be able to 
download a tarball of project source, issues, and wikis. These tarballs will be 
available throughout the rest of 2016.

I just want to make sure the project doesn't just disappear one day, or that 
everything is lost.

Thanks and hope to hear from somebody soon.
```

Original issue reported on code.google.com by `vgturtle...@gmail.com` on 26 Mar 2015 at 11:10

**Comment by vgturtle127** [comment]
Original poster here. Thanks for doing the export. I can't remember if it worked for me or not, but will this be the official continuation of this project?

**Comment by piorrro33** [comment]
I don't know if it will be the official continuation, but I hope so since it took me a bit of time to correct everything.
The only problem is that I don't know how to upload the last release they made. :/
I'll make a build of the last SVN version and upload it.

**Comment by piorrro33** [comment]
And the first GitHub release is done. https://github.com/piorrro33/psxjin/releases/tag/SVN%2F2015-07-03

**Comment by vgturtle127** [comment]
Is that a version compiled today? Or just the old release packaged today?

**Comment by piorrro33** [comment]
Yeah, this version was compiled today with today's code. (now yesterday) I'll also try to upload the old release.

**Comment by piorrro33** [comment]
Just a little question : is the .sdf file mandatory or I can remove it? Because it's a really big file to upload.

**Comment by vgturtle127** [comment]
I think the SDF file can be removed. I haven't seen it in any other repositories, so I think we are good. :smile:

**Comment by vgturtle127** [comment]
I removed the SDF file.

**Comment by piorrro33** [comment]
I added it to the .gitignore, with many other files types.

**Comment by vgturtle127** [comment]
Thanks!

**Comment by piorrro33** [comment]
Done with the import, issue closed.
